var usuario = 'EUR-' + '1702758';
var token = 'd0311615eaba3651ca8215fe2c3254ed2c85c398';
var nick = 'n';
var delay = '4';
var duracion = '10000000';
var sorteosSem = '2';
var vueltas = '8';
//var precioSort = 2.20;//definido en lang PRECIO tambien
var precioSort = Number("2.50");
var weight = 1; // New weight variable

$('#veces').html("User ID: EUR-1702758");
$('#textoperiodo').html("<p>Period: Until 5+2 appears </p>");
$(function () {
    function G(b) { 
        for (var c = b.length, p, m; c--;) {
            p = Math.floor(Math.random() * (c + 1));
            if (Math.random() * 100 < weight) { // Adjusting for weight
                p = c; // Increase the chance of getting the same number
            }
            m = b[c], b[c] = b[p], b[p] = m; 
        }
        return b; 
    }
    function I() {
        1 == aleatorio && (arr = G([31, 13, 32, 49, 50, 33, 42, 43, 34, 35, 3, 7, 16, 17, 18, 20, 21, 45, 46, 1, 47, 48, 22, 23, 26, 27, 8, 2, 4, 9, 10, 12, 11, 14, 15, 28, 30, 36, 19, 37, 38, 39, 40, 41, 44, 24, 5, 29, 6, 25]).splice(0, 5), est = G([10, 8, 3, 12, 4, 9, 7, 2, 5, 6, 1, 11]).splice(0, 2), $("#tucombinacion").html("Your combination: <b>" + arr[0] + "</b> | <b>" + arr[1] + "</b> | <b>" + arr[2] + "</b> | <b>" + arr[3] + "</b> | <b>" + arr[4] + "</b> | &#10025;<b>" +
            est[0] + "</b>  &#10025;<b>" + est[1] + "</b>")); var b = document; la = G([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]); ha = la.splice(0, 5); for (var c = [], p = 0; p < arr.length; p++)-1 !== ha.indexOf(arr[p]) && c.push(arr[p]); var m = G([10, 12, 3, 11, 2, 6, 4, 9, 5, 7, 8, 1]); r = G(m); r = m.splice(0, 2); m = []; for (p = 0; 2 > p; p++)-1 !== r.indexOf(est[p]) && m.push(est[p]); B += precioSort; F += 1; 6 == F && (F = 1); b.getElementById("a" + F).innerHTML = '<div class="cb"><span class="cb1">' +
                n + ' </span><span class="cb2">' + ha + '</span><span class="cb3">' + r + '</span><span class="cb4"> </span><span class="cb5 aciertos-' + c.length + "-" + m.length + '">' + c + '</span><span class="cb6 star1-' + c.length + "-" + m.length + '"> &#10025;' + m[0] + '</span><span class="cb6 star2-' + c.length + "-" + m.length + '"> &#10025;' + m[1] + "</span></div>"; $("#a" + F).parent().prepend($("#a" + F)); if (n == d * A) {
                    delay = 1E3; --l; --g; --J; 20 == d ? $("#textoldt").html("Matches shown <span class='color-2-1'> 2+1</span>, <span class='color-1-2'> 1+2</span>, <span class='color-3-0'> 3+0</span>, <span class='color-3-1'> 3+1</span>, <span class='color-2-2'> 2+2</span>, <span class='color-3-2'> 3+2</span>, <span class='color-4-0'> 4+0</span>, <span class='color-4-1'> 4+1</span>, <span class='color-4-2'> 4+2</span>, <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>") :
                        40 == d ? $("#textoldt").html("Matches shown <span class='color-1-2'> 1+2</span>, <span class='color-3-0'> 3+0</span>, <span class='color-3-1'> 3+1</span>, <span class='color-2-2'> 2+2</span>, <span class='color-3-2'> 3+2</span>, <span class='color-4-0'> 4+0</span>, <span class='color-4-1'> 4+1</span>, <span class='color-4-2'> 4+2</span>, <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>") : 80 == d ? $("#textoldt").html("Matches shown <span class='color-3-0'> 3+0</span>, <span class='color-3-1'> 3+1</span>, <span class='color-2-2'> 2+2</span>, <span class='color-3-2'> 3+2</span>, <span class='color-4-0'> 4+0</span>, <span class='color-4-1'> 4+1</span>, <span class='color-4-2'> 4+2</span>, <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>") :
                            160 == d ? $("#textoldt").html("Matches shown <span class='color-2-2'> 2+2</span>, <span class='color-3-2'> 3+2</span>, <span class='color-4-0'> 4+0</span>, <span class='color-4-1'> 4+1</span>, <span class='color-4-2'> 4+2</span>, <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>") : 320 == d ? $("#textoldt").html("Matches shown <span class='color-3-2'> 3+2</span>, <span class='color-4-0'> 4+0</span>, <span class='color-4-1'> 4+1</span>, <span class='color-4-2'> 4+2</span>, <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>") :
                                1280 == d ? $("#textoldt").html("Matches shown <span class='color-3-2'> 3+2</span>, <span class='color-4-0'> 4+0</span>, <span class='color-4-1'> 4+1</span>, <span class='color-4-2'> 4+2</span>, <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>") : 2560 == d ? $("#textoldt").html("Matches shown <span class='color-4-0'> 4+0</span>, <span class='color-4-1'> 4+1</span>, <span class='color-4-2'> 4+2</span>, <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>") :
                                    5120 == d ? $("#textoldt").html("Matches shown <span class='color-4-0'> 4+0</span>, <span class='color-4-1'> 4+1</span>, <span class='color-4-2'> 4+2</span>, <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>") : 10240 == d ? $("#textoldt").html("Matches shown <span class='color-4-1'> 4+1</span>,<span class='color-4-2'> 4+2</span>, <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>") :
                                        20480 == d ? $("#textoldt").html("Matches shown <span class='color-4-2'> 4+2</span>, <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>") : 163840 == d && $("#textoldt").html("Matches shown <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>"); $("#pf2").text(Math.round(d) + " years"); d *= 2; ia = y / (d * A); ma += 2; $("#indicador").css({ left: y / 2 }); $("#pf3").text(Math.round(d) + " years"); $("#ldt ul").append("<li id= tr" +
                                            d + ">" + d + "</li><li id= t" + d + ">" + d + "</li>"); var C = d / ma, x = 1, ta = y / $("#ldt li").size() * 100 / y; $("#ldt li").each(function (q) { x += 100; $(this).delay(x).css({ width: ta + "%" }); 20481 > d ? $(this).delay(x).text(Math.round(C * q)) : $(this).delay(x).text(""); 1E3 < d && 550 > y && $(this).delay(x).text("") }); $("#premiosldt li").each(function (q) {
                                                x += 100; q = $(this).position().left; var h = l; $(this).is(".icono2-0") && 1 > J && ($(this).remove(), $(this)); $(this).is(".icono2-0") && (h = J); $(this).is(".icono2-0") && 20 < d && ($(this).remove(), $(this));
                                                $(this).is(".icono2-1") && (h = l + 1); $(this).is(".icono2-1") && 40 < d && ($(this).remove(), $(this)); $(this).is(".icono1-2") && (h = l + 1); $(this).is(".icono1-2") && 80 < d && ($(this).remove(), $(this)); $(this).is(".icono3-0") && (h = l + 2); $(this).is(".icono3-0") && 160 < d && ($(this).remove(), $(this)); $(this).is(".icono3-1") && (h = l + 2); $(this).is(".icono3-1") && 160 < d && ($(this).remove(), $(this)); $(this).is(".icono2-2") && (h = l + 3); $(this).is(".icono2-2") && 320 < d && ($(this).remove(), $(this)); $(this).is(".icono3-2") && (h = l + 5, 1 > h && (h = 1));
                                                $(this).is(".icono3-2") && 2560 < d && ($(this).remove(), $(this)); $(this).is(".icono4-0") && (h = l + 7, 1 > h && (h = 1)); $(this).is(".icono4-0") && 10240 < d && ($(this).remove(), $(this)); $(this).is(".icono4-1") && (h = l + 8, 3 > h && (h = 3)); $(this).is(".icono4-1") && 20480 < d && ($(this).remove(), $(this)); $(this).is(".icono4-2") && (h = l + 10, 4 > h && (h = 4)); $(this).is(".icono4-2") && 163840 < d && ($(this).remove(), $(this)); $(this).is(".icono5-0") && (h = l + 11, 5 > h && (h = 5)); $(this).is(".icono5-1") && (h = l + 14, 7 > h && (h = 7)); $(this).is(".icono5-2") && (h = l + 16, 9 >
                                                    h && (h = 9)); $(this).addClass("reduce").css({ left: q / 2, width: h })
                                            }); $("#tr" + d).css({ "background-color": "#cccccc" }); $("#t" + d).css({ "background-color": "#f3f3f3" }); $("#velocidad2_opc").trigger("change")
                } else g = ia * n, $("#indicador").css({ left: g }); K = 365 / A * n; a = Math.floor(K / 365); k = Math.floor((K - 365 * a) / 30); t = Math.ceil(K - 365 * a - 30 * k); switch (c.length + "-" + m.length) {
                    case "2-0": ale = r[0]; estepremio = ua[ale] + .19 * ale; f += estepremio; e[0]++; L = 0 == L ? estepremio : (L + estepremio) / 2; b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) +
                        " \u20ac"; b.getElementById("d2-0").innerHTML = "Match 2 + 0:  <b>" + e[0] + "</b>"; b.getElementById("media2-0").innerHTML = L.toFixed(2) + "\u20ac"; M++; na == a ? M > N && (N = M, b.getElementById("logros2-0").innerHTML = "<p>Your best ANNUAL data for matching 2+0 was " + N + " times, around year " + a + " (" + parseFloat(100 * N / A).toFixed(4) + "%)</p>") : (M = 0, na = a); 21 > d && (c = $("#indicador").position().left, $("#premiosldt ul").append($("<li></li>").addClass("icono2-0").css({ left: c, width: J }))); break; case "2-1": ale = r[0]; estepremio = va[ale] +
                            .19 * ale; f += estepremio; e[1]++; O = 0 == O ? estepremio : (O + estepremio) / 2; b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) + " \u20ac"; b.getElementById("d2-1").innerHTML = "Match 2 + 1:  <b>" + e[1] + "</b>"; b.getElementById("media2-1").innerHTML = O.toFixed(2) + "\u20ac"; P++; oa == a ? P > Q && (Q = P, b.getElementById("logros2-1").innerHTML = "<p>Your best ANNUAL data for matching 2+1 was " + Q + " times, around year " + a + " (" + parseFloat(100 * Q / A).toFixed(4) + "%)</p>") : (P = 0, oa = a); 41 > d && (c = $("#indicador").position().left, g = l +
                                1, $("#premiosldt ul").append($("<li></li>").addClass("icono2-1").css({ left: c, width: g }))); break; case "1-2": ale = r[0]; estepremio = wa[ale] + .05 * ale; f += estepremio; e[2]++; R = 0 == R ? estepremio : (R + estepremio) / 2; b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) + " \u20ac"; b.getElementById("d1-2").innerHTML = "Match 1 + 2:  <b>" + e[2] + "</b>"; b.getElementById("media1-2").innerHTML = R.toFixed(2) + \u20ac; S++; pa == a ? S > T && (T = S, b.getElementById("logros1-2").innerHTML = "<p>Your best ANNUAL data for matching 1+2 was " +
                                    T + " times, around year " + a + " (" + parseFloat(100 * T / A).toFixed(4) + "%)</p>") : (S = 0, pa = a); 81 > d && (c = $("#indicador").position().left, g = l + 1, 2 > g && (g = 1), $("#premiosldt ul").append($("<li></li>").addClass("icono1-2").css({ left: c, width: g }))); break; case "3-0": ale = r[0]; estepremio = xa[ale] + .33 * ale; f += estepremio; 0 == e[3] && (0 == a && 0 == k ? b.getElementById("logros3-0").innerHTML = "<p>Strong start! You have matched 3+0 in " + t + " days!!</p>" : 0 == a ? b.getElementById("logros3-0").innerHTML = "<p>Your first 3+0 match was in just " +
                                        k + " months!!</p>" : 1 == a ? b.getElementById("logros3-0").innerHTML = "<p>Your first 3+0 match was in just a year and " + k + " months!!</p>" : 2 <= a && 10 >= a ? b.getElementById("logros3-0").innerHTML = "<p>Your first 3+0 match has been in " + a + " years!!</p>" : 11 <= a && 30 >= a ? b.getElementById("logros3-0").innerHTML = "<p>Your first 3+0 match finally emerged after " + a + " years</p>" : 30 < a && (0 == e[4] ? b.getElementById("logros3-0").innerHTML = "<p>Your first 3+0 match took " + a + " years!! Shameful!!</p>" : b.getElementById("logros3-0").innerHTML =
                                            "<p>Your first 3+0 match took nothing but " + a + " years!! You were lucky to win higher prizes in that period!!</p>")); e[3]++; U = 0 == U ? estepremio : (U + estepremio) / 2; b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) + " \u20ac"; b.getElementById("d3-0").innerHTML = "Match 3 + 0:  <b>" + e[3] + "</b>"; b.getElementById("media3-0").innerHTML = U.toFixed(2) + \u20ac; 161 > d && (c = $("#indicador").position().left, g = l + 2, $("#premiosldt ul").append($("<li></li>").addClass("icono3-0").css({ left: c, width: g }))); break; case "3-1": ale =
                                                r[0]; estepremio = ya[ale] + .28 * ale; f += estepremio; 0 == e[4] && (0 == a && 0 == k ? b.getElementById("logros3-1").innerHTML = "<p>Strong start! You have matched 3+1 in " + t + " days!!</p>" : 0 == a ? b.getElementById("logros3-1").innerHTML = "<p>Your first 3+1 match was in just " + k + " months!!</p>" : 1 == a ? b.getElementById("logros3-1").innerHTML = "<p>Your first 3+1 match was in just a year and " + k + " months!!</p>" : 2 <= a && 10 >= a ? b.getElementById("logros3-1").innerHTML = "<p>Your first 3+1 match has been in " + a + " years!!</p>" : 11 <= a && 30 >=
                                                    a ? b.getElementById("logros3-1").innerHTML = "<p>Your first 3+1 match finally emerged after " + a + " years</p>" : 30 < a && (0 == e[5] ? b.getElementById("logros3-1").innerHTML = "<p>Your first 3+1 match took " + a + " years!! Shameful!!</p>" : b.getElementById("logros3-1").innerHTML = "<p>Your first 3+1 match took nothing but " + a + " years!! You were lucky to win higher prizes in that period!!</p>")); e[4]++; V = 0 == V ? estepremio : (V + estepremio) / 2; b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) + " \u20ac"; b.getElementById("d3-1").innerHTML =
                                                        "Match 3 + 1:  <b>" + e[4] + "</b>"; b.getElementById("media3-1").innerHTML = V.toFixed(2) + \u20ac; 321 > d && (c = $("#indicador").position().left, g = l + 2, $("#premiosldt ul").append($("<li></li>").addClass("icono3-1").css({ left: c, width: g }))); break; case "2-2": ale = r[0]; estepremio = za[ale] + .19 * ale; f += estepremio; 0 == e[5] && (0 == a && 0 == k ? b.getElementById("logros2-2").innerHTML = "<p>Strong start! You have matched 2+2 in " + t + " days!!</p>" : 0 == a ? b.getElementById("logros2-2").innerHTML = "<p>Your first 2+2 match was in just " + k +
                                                            " months!!</p>" : 1 == a ? b.getElementById("logros2-2").innerHTML = "<p>Your first 2+2 match was in just a year and " + k + " months!!</p>" : 2 <= a && 10 >= a ? b.getElementById("logros2-2").innerHTML = "<p>Your first 2+2 match has been in " + a + " years!!</p>" : 11 <= a && 30 >= a ? b.getElementById("logros2-2").innerHTML = "<p>Your first 2+2 match finally emerged after " + a + " years</p>" : 30 < a && (0 == e[6] ? b.getElementById("logros2-2").innerHTML = "<p>Your first 2+2 match took " + a + " years!! Shameful!!</p>" : b.getElementById("logros2-2").innerHTML =
                                                                "<p>Your first 2+2 match took nothing but " + a + " years!! You were lucky to win higher prizes in that period!!</p>")); e[5]++; W = 0 == W ? estepremio : (W + estepremio) / 2; b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) + " \u20ac"; b.getElementById("d2-2").innerHTML = "Match 2 + 2:  <b>" + e[5] + "</b>"; b.getElementById("media2-2").innerHTML = W.toFixed(2) + \u20ac; 321 > d && (c = $("#indicador").position().left, g = l + 3, $("#premiosldt ul").append($("<li></li>").addClass("icono2-2").css({ left: c, width: g }))); break; case "3-2": ale =
                                                                    r[0]; estepremio = Aa[ale] + .71 * ale; f += estepremio; 0 == e[6] && (0 == a && 0 == k ? b.getElementById("logros3-2").innerHTML = "<p>Strong start! You have matched 3+2 in " + t + " days!!</p>" : 0 == a ? b.getElementById("logros3-2").innerHTML = "<p>Your first 3+2 match was in just " + k + " months!!</p>" : 1 == a ? b.getElementById("logros3-2").innerHTML = "<p>Your first 3+2 match was in just a year and " + k + " months!!</p>" : 2 <= a && 10 >= a ? b.getElementById("logros3-2").innerHTML = "<p>Your first 3+2 match has been in " + a + " years!!</p>" : 11 <= a && 30 >=
                                                                        a ? b.getElementById("logros3-2").innerHTML = "<p>Your first 3+2 match finally emerged after " + a + " years</p>" : 30 < a && (0 == e[7] ? b.getElementById("logros3-2").innerHTML = "<p>Your first 3+2 match took " + a + " years!! Shameful!!</p>" : b.getElementById("logros3-2").innerHTML = "<p>Your first 3+2 match took nothing but " + a + " years!! You were lucky to win higher prizes in that period!!</p>")); e[6]++; X = 0 == X ? estepremio : (X + estepremio) / 2; b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) + " \u20ac"; b.getElementById("d3-2").innerHTML =
                                                                            "Match 3 + 2:  <b>" + e[6] + "</b>"; b.getElementById("media3-2").innerHTML = X.toFixed(2) + \u20ac; 2561 > d && (c = $("#indicador").position().left, g = l + 5, 1 > g && (g = 1), $("#premiosldt ul").append($("<li></li>").addClass("icono3-2").css({ left: c, width: g }))); break; case "4-0": ale = r[0]; estepremio = Ba[ale] + .27 * ale; f += estepremio; 0 == e[7] && (0 == a && 0 == k ? b.getElementById("logros4-0").innerHTML = "<p>Strong start! You have matched 4+0 in " + t + " days!!</p>" : 0 == a ? b.getElementById("logros4-0").innerHTML = "<p>Your first 4+0 match was in just " +
                                                                                k + " months!!</p>" : 1 == a ? b.getElementById("logros4-0").innerHTML = "<p>Your first 4+0 match was in just a year and " + k + " months!!</p>" : 2 <= a && 10 >= a ? b.getElementById("logros4-0").innerHTML = "<p>Your first 4+0 match has been in " + a + " years!!</p>" : 11 <= a && 30 >= a ? b.getElementById("logros4-0").innerHTML = "<p>Your first 4+0 match finally emerged after " + a + " years</p>" : 30 < a && (0 == e[8] ? b.getElementById("logros4-0").innerHTML = "<p>Your first 4+0 match took " + a + " years!! Shameful!!</p>" : b.getElementById("logros4-0").innerHTML =
                                                                                    "<p>Your first 4+0 match took nothing but " + a + " years!! You were lucky to win higher prizes in that period!!</p>")); e[7]++; Y = 0 == Y ? estepremio : (Y + estepremio) / 2; b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) + " \u20ac"; b.getElementById("d4-0").innerHTML = "Match 4 + 0:  <b>" + e[7] + "</b>"; b.getElementById("media4-0").innerHTML = Y.toFixed(2) + \u20ac; if (10241 > d) { c = $("#indicador").position().left; var g = l + 7; 2 > g && (g = 1); $("#premiosldt ul").append($("<li></li>").addClass("icono4-0").css({ left: c, width: g })) } break;
                    case "4-1": ale = r[0]; estepremio = Ca[ale] + .05 * ale; f += estepremio; 0 == e[8] && (0 == a && 0 == k ? b.getElementById("logros4-1").innerHTML = "<p>Strong start! You have matched 4+1 in " + t + " days!!</p>" : 0 == a ? b.getElementById("logros4-1").innerHTML = "<p>Your first 4+1 match was in just " + k + " months!!</p>" : 1 == a ? b.getElementById("logros4-1").innerHTML = "<p>Your first 4+1 match was in just a year and " + k + " months!!</p>" : 2 <= a && 10 >= a ? b.getElementById("logros4-1").innerHTML = "<p>Your first 4+1 match has been in " + a + " years!!</p>" :
                        11 <= a && 70 >= a ? b.getElementById("logros4-1").innerHTML = "<p>Your first 4+1 match finally emerged after " + a + " years</p>" : 71 <= a && 499 >= a ? b.getElementById("logros4-1").innerHTML = "<p>Your first 4+1 match finally emerged after " + a + " years. Late!</p>" : 500 < a && (0 == e[9] ? b.getElementById("logros4-1").innerHTML = "<p>Your first 4+1 match took " + a + " years!! Shameful!!</p>" : b.getElementById("logros4-1").innerHTML = "<p>Your first 4+1 match took nothing but " + a + " years!! You were lucky to win higher prizes in that period!!</p>"));
                        e[8]++; Z = 0 == Z ? estepremio : (Z + estepremio) / 2; b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) + " \u20ac"; b.getElementById("d4-1").innerHTML = "Match 4 + 1:  <b>" + e[8] + "</b>"; b.getElementById("media4-1").innerHTML = Z.toFixed(2) + \u20ac; 20481 > d && (c = $("#indicador").position().left, g = l + 8, 3 > g && (g = 3), $("#premiosldt ul").append($("<li></li>").addClass("icono4-1").css({ left: c, width: g }))); break; case "4-2": ale = r[0]; ale2 = Math.ceil(800 * Math.random()) + 8; f = f + aa[ale] + ale2; 0 == e[9] && (0 == a && 0 == k ? b.getElementById("logros4-2").innerHTML =
                            "<p>Impressive!!! You have matched 4+2 in " + t + " days!!</p>" : 0 == a ? b.getElementById("logros4-2").innerHTML = "<p>Your first 4+2 match was in just " + k + " months!! Run to your nearest retailer!!</p>" : 1 == a ? b.getElementById("logros4-2").innerHTML = "<p>Your first 4+2 match was in just a year and " + k + " months!! BRAVO!</p>" : 2 <= a && 10 >= a ? b.getElementById("logros4-2").innerHTML = "<p>Your first 4+2 match has been in " + a + " years!! \u00a1Excellent!</p>" : 11 <= a && 30 >= a ? b.getElementById("logros4-2").innerHTML = "<p>Your first 4+2 match finally emerged after " +
                                a + " years. Very good.</p>" : 31 <= a && 50 >= a ? b.getElementById("logros4-2").innerHTML = "<p>Your first 4+2 match finally emerged after " + a + " years. Acceptable.</p>" : 51 <= a && 100 >= a ? b.getElementById("logros4-2").innerHTML = "<p>Your first 4+2 match finally emerged after " + a + " years. So-so...just acceptable.</p>" : 101 <= a && 2E3 >= a ? b.getElementById("logros4-2").innerHTML = "<p>Your first 4+2 match finally emerged after " + a + " years... Better late than never.</p>" : 2001 <= a && 3E3 >= a ? b.getElementById("logros4-2").innerHTML =
                                    "<p>Your first 4+2 match finally emerged after " + a + " years... Too little, too late...</p>" : 3001 < a && (0 == e[10] ? b.getElementById("logros4-2").innerHTML = "<p>Your first 4+2 match took " + a + " years!! Awful!</p>" : b.getElementById("logros4-2").innerHTML = "<p>Your first 4+2 match took nothing but " + a + " years!! Awful!! You were lucky to win higher prizes in that period!!</p>"), 1 == aleatorio && $("<p>Your quick pick for this 4+2 prize was: <b>" + arr[0] + "</b> | <b>" + arr[1] + "</b> | <b>" + arr[2] + "</b> | <b>" + arr[3] + "</b> | <b>" +
                                        arr[4] + "</b> | &#10025;<b>" + est[0] + "</b>  &#10025;<b>" + est[1] + "</b></p>").appendTo("#logros4-2")); e[9]++; 1 == e[9] && (c = aa[ale] + ale2, u = f - 2 * n, c = { xUsuario: usuario, xToken: token, xNick: nick, xA: ale, xA2: ale2, xEuro1: arr[0], xEuro2: arr[1], xEuro3: arr[2], xEuro4: arr[3], xEuro5: arr[4], xEuro6: est[0], xEuro7: est[1], xPremio: "4+2", xCantidad: c, xSemanal: sorteosSem, xTotal: n, xGanado: f, xBalance: u, xAno: a, xMes: k, xDia: t, xSorteo: n }, $.ajax({
                                            url: "https://www.cuandomevaatocar.com/includes/puntuaciones-eur.php", type: "POST", dataType: "json", data: c, success: function (q,
                                                h, D) { "success" == q.status && ("n" != nick ? $("#logros4-2").append('<div class="enviarhof"><div class="marcohof"><div class="imagenhof"><img width="100%" src="https://www.cuandomevaatocar.com/img/hall-of-fame.png" alt="Prize saved to Hall Of Fame"></div><div class="formhof"><h3><span>New record! This result is among the best!</span></h3><h3><span>Your prize was saved to </span></h3><h2><span><a href="https://www.cuandomevaatocar.com/en/hall-of-fame/euromillions/">Hall of Fame</a></span></h2></div></div></div><div class="clear"></div>') : $("#logros4-2").append('<div class="enviarhof"><div class="marcohof"><div class="imagenhof"><img width="100%" src="https://www.cuandomevaatocar.com/img/hall-of-fame.png" alt="Prize saved to Hall Of Fame"></div><div class="formhof"><h3><span>New record! This result is among the best!</span></h3><form id="formoid42" action="https://www.cuandomevaatocar.com/includes/actualizarnombre-eur.php" title="" method="post"><div class="hofizq"><label class="title">Name or nick</label><input type="text" id="xNick42" name="xNick42" maxlength="12" required pattern="[a-zA-Z0-9 ]+" ><h5>Only letters and numbers, no special characters. If you leave it blank you will appear as anonymous</h5><input type="hidden" id="xUsuario42" name="xUsuario42" value=""><input type="hidden" id="xToken42" name="xToken42" value=""><br>How do you want your combination to be shown?<br><input type="radio" name="xPriv" value="0" checked>Complete <span>(Example: 2 | 6 | 11 | 27 | 32 | &#10025; 2 | &#10025; 9 )</span><br><input type="radio" name="xPriv" value="1">Incomplete <span>(Example: ** | 6 | 11 | ** | 32 | &#10025; ** | &#10025; 9 )</span><br><input type="radio" name="xPriv" value="2">Hidden <span>(Example: ** | ** | ** | ** | ** | &#10025; ** |  &#10025; ** )</span></div><div class="hofder"><input type="submit" id="submitButton42" name="submitButton42" value="Save"></div></form></div></div></div><div class="clear"></div>')) },
                                            error: function (q, h, D) { }
                                        })); ga("send", "event", { eventCategory: "Euromillones - Premio de 4+2", eventAction: usuario, eventLabel: a }); ba = 0 == ba ? aa[ale] + ale2 + .24 * ale : (ba + aa[ale] + ale2) / 2; b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) + " \u20ac"; b.getElementById("d4-2").innerHTML = "Match 4 + 2:  <b>" + e[9] + "</b>"; b.getElementById("media4-2").innerHTML = ba.toFixed(2) + \u20ac; 163840 >= d && (c = $("#indicador").position().left, g = l + 10, 4 > g && (g = 4), $("#premiosldt ul").append($("<li></li>").addClass("icono4-2").css({
                                            left: c,
                                            width: g
                                        }))); break; case "5-0": ale2 = Math.ceil(2E3 * Math.random()) + 50; ale = r[0]; f = f + v[ale] + ale2; 0 == e[10] && (0 == a && 0 == k ? b.getElementById("logros5-0").innerHTML = "<p>You're a boss! You have matched 5+0 in " + t + " days!! THAT'S LUCKING OUT!!Your prize would have been " + (v[ale] + ale2) + "\u20ac</p>" : 0 == a ? b.getElementById("logros5-0").innerHTML = "<p>Awesome! Your first 5+0 match was in just " + k + " months!! Congratulations!! Your prize would have been " + (v[ale] + ale2) + "\u20ac</p>" : 1 == a ? b.getElementById("logros5-0").innerHTML =
                                            "<p>Well done!! Your first 5+0 match was in just a year and " + k + " months!! Your prize would have been " + (v[ale] + ale2) + "\u20ac</p>" : 5 <= a && 10 >= a ? b.getElementById("logros5-0").innerHTML = "<p>Your first 5+0 match has been in " + a + " years!! \u00a1\u00a1No est\u00e1 nada mal!! Your prize would have been " + (v[ale] + ale2) + "\u20ac</p>" : 11 <= a && 25 >= a ? b.getElementById("logros5-0").innerHTML = "<p>Your first 5+0 match has been in " + a + " years!! \u00a1\u00a1Eres m\u00e1s afortunado que la mayor\u00eda!! Your prize would have been " +
                                                (v[ale] + ale2) + "\u20ac</p>" : 26 <= a && 80 >= a ? b.getElementById("logros5-0").innerHTML = "<p>Your first 5+0 match has been in " + a + " years!! \u00a1Es un buen resultado! Your prize would have been " + (v[ale] + ale2) + "\u20ac</p>" : 81 <= a && 499 >= a ? b.getElementById("logros5-0").innerHTML = "<p>Your first 5+0 match took " + a + " years. Your prize would have been " + (v[ale] + ale2) + "\u20ac</p>" : 500 <= a && 999 >= a ? b.getElementById("logros5-0").innerHTML = "<p>Your first 5+0 match finally emerged after " + a + " years \u00a1Un poco tarde...! Your prize would have been " +
                                                    (v[ale] + ale2) + "\u20ac</p>" : 500 <= a && 999 >= a ? b.getElementById("logros5-0").innerHTML = "<p>Your first 5+0 match finally emerged after " + a + " years A little late! Your prize would have been " + (v[ale] + ale2) + "\u20ac</p>" : 1E3 < a && (0 == e[11] ? b.getElementById("logros5-0").innerHTML = "<p>Your first 5+0 match took " + a + " years!! Too late! Your prize would have been " + (v[ale] + ale2) + "\u20ac</p>" : b.getElementById("logros5-0").innerHTML = "<p>Your first 5+0 match took nothing but " + a + " years!! You were lucky to win higher prizes in that period!! Your prize would have been " +
                                                        (v[ale] + ale2) + "\u20ac</p>"), 1 == aleatorio && $("<p>Your quick pick for this 5+0 prize was: <b>" + arr[0] + "</b> | <b>" + arr[1] + "</b> | <b>" + arr[2] + "</b> | <b>" + arr[3] + "</b> | <b>" + arr[4] + "</b> | &#10025;<b>" + est[0] + "</b>  &#10025;<b>" + est[1] + "</b></p>").appendTo("#logros5-0")); e[10]++; 1 == e[10] && (c = v[ale] + ale2, u = f - 2 * n, c = {
                                                            xUsuario: usuario, xToken: token, xNick: nick, xA: ale, xA2: ale2, xEuro1: arr[0], xEuro2: arr[1], xEuro3: arr[2], xEuro4: arr[3], xEuro5: arr[4], xEuro6: est[0], xEuro7: est[1], xPremio: "5+0", xCantidad: c, xSemanal: sorteosSem,
                                                            xTotal: n, xGanado: f, xBalance: u, xAno: a, xMes: k, xDia: t, xSorteo: n
                                                        }, $.ajax({
                                                            url: "https://www.cuandomevaatocar.com/includes/puntuaciones-eur.php", type: "POST", dataType: "json", data: c, success: function (q, h, D) {
                                                                "success" == q.status && ("n" != nick ? $("#logros5-0").append('<div class="enviarhof"><div class="marcohof"><div class="imagenhof"><img width="100%" src="https://www.cuandomevaatocar.com/img/hall-of-fame.png" alt="Prize saved to Hall Of Fame"></div><div class="formhof"><h3><span>New record! This result is among the best!</span></h3><h3><span>Your prize was saved to </span></h3><h2><span><a href="https://www.cuandomevaatocar.com/en/hall-of-fame/euromillions/">Hall of Fame</a></span></h2></div></div></div><div class="clear"></div>') :
                                                                    $("#logros5-0").append('<div class="enviarhof"><div class="marcohof"><div class="imagenhof"><img width="100%" src="https://www.cuandomevaatocar.com/img/hall-of-fame.png" alt="Prize saved to Hall Of Fame"></div><div class="formhof"><h3><span>New record! This result is among the best!</span></h3><form id="formoid50" action="https://www.cuandomevaatocar.com/includes/actualizarnombre-eur.php" title="" method="post"><div class="hofizq"><label class="title">Name or nick</label><input type="text" id="xNick50" name="xNick50" maxlength="12" required pattern="[a-zA-Z0-9 ]+" ><h5>Only letters and numbers, no special characters. If you leave it blank you will appear as anonymous</h5><input type="hidden" id="xUsuario50" name="xUsuario50" value=""><input type="hidden" id="xToken50" name="xToken50" value=""><br>How do you want your combination to be shown?<br><input type="radio" name="xPriv" value="0" checked>Complete <span>(Example: 2 | 6 | 11 | 27 | 32 | &#10025; 2 | &#10025; 9 )</span><br><input type="radio" name="xPriv" value="1">Incomplete <span>(Example: ** | 6 | 11 | ** | 32 | &#10025; ** | &#10025; 9 )</span><br><input type="radio" name="xPriv" value="2">Hidden <span>(Example: ** | ** | ** | ** | ** | &#10025; ** |  &#10025; ** )</span></div><div class="hofder"><input type="submit" id="submitButton50" name="submitButton50" value="Save"></div></form></div></div></div><div class="clear"></div>'))
                                                            },
                                                            error: function (q, h, D) { }
                                                        })); ga("send", "event", { eventCategory: "Euromillones - Premio de 5+0", eventAction: usuario, eventLabel: a }); ca = 0 == ca ? v[ale] + ale2 + .04 * ale : (ca + v[ale] + ale2) / 2; 1 < e[10] && (c = a - qa, c < da && (da = c, 0 == da ? b.getElementById("logros5-0-2").innerHTML = "<p>You won two 5+0 prizes in the same year!!! You were incredibly lucky!!!</p>" : b.getElementById("logros5-0-2").innerHTML = "<p>The shortest distance between your 5+0 prizes was was " + da + " years around year " + a + "</p>")); qa = a; b.getElementById("ganado").innerHTML =
                                                            parseFloat(f).toFixed(2) + " \u20ac"; b.getElementById("d5-0").innerHTML = "Match 5 + 0:  <b>" + e[10] + "</b>"; b.getElementById("media5-0").innerHTML = ca.toFixed(2) + \u20ac; c = $("#indicador").position().left; g = l + 11; 4 > g && (g = 4); $("#premiosldt ul").append($("<li></li>").addClass("icono5-0").css({ left: c, width: g })); 4 < e[10] && 500 < 100 * f / B && (c = confirm("Will you behave?"), window.location.href = 1 == c ? "https://www.cuandomevaatocar.com" : "https://www.google.com"); break; case "5-1": ale2 = Math.ceil(15E4 * Math.random()) + 1E4; ale =
                                                                r[0]; f = f + w[ale] + ale2; 0 == e[11] && (0 == a && 0 == k ? b.getElementById("logros5-1").innerHTML = "<p>RUN TO YOUR NEAREST RETAILER! NOW!! You have matched 5+1 in " + t + " days!! THAT'S LUCKING OUT!! Your prize would have been " + (w[ale] + ale2) + "\u20ac</p>" : 0 == a ? b.getElementById("logros5-1").innerHTML = "<p>UNBELIEVABLE!! Your first 5+1 match was in just " + k + " months!! Congratulations!! Your prize would have been " + (w[ale] + ale2) + "\u20ac</p>" : 1 == a ? b.getElementById("logros5-1").innerHTML = "<p>AWESOME!! Your first 5+1 match was in just a year and " +
                                                                    k + " months!! Your prize would have been " + (w[ale] + ale2) + "\u20ac</p>" : 5 <= a && 10 >= a ? b.getElementById("logros5-1").innerHTML = "<p>BRAVO! Your first 5+1 match has been in " + a + " years!! Your prize would have been " + (w[ale] + ale2) + "\u20ac</p>" : 11 <= a && 25 >= a ? b.getElementById("logros5-1").innerHTML = "<p>Your first 5+1 match has been in " + a + " years!! You're luckiest than 99,9999% of people!! Your prize would have been " + (w[ale] + ale2) + "\u20ac</p>" : 26 <= a && 80 >= a ? b.getElementById("logros5-1").innerHTML = "<p>Your first 5+1 match was in just " +
                                                                        a + " years!! Your prize would have been " + (w[ale] + ale2) + "\u20ac</p>" : 81 <= a && 299 >= a ? b.getElementById("logros5-1").innerHTML = "<p>Your first 5+1 match took " + a + " years. It seems late but actually it's soon! Your prize would have been " + (w[ale] + ale2) + "\u20ac</p>" : 299 <= a && 700 >= a ? b.getElementById("logros5-1").innerHTML = "<p>Your first 5+1 match finally emerged after " + a + " years It has been a long time coming but it is acceptable! Your prize would have been " + (w[ale] + ale2) + "\u20ac</p>" : 701 <= a && 999 >= a ? b.getElementById("logros5-1").innerHTML =
                                                                            "<p>Your first 5+1 match finally emerged after " + a + " years It's soon! Your prize would have been " + (w[ale] + ale2) + "\u20ac</p>" : 1E3 <= a && 1E4 >= a ? b.getElementById("logros5-1").innerHTML = "<p>Your first 5+1 match took " + a + " years!! Your prize would have been " + (w[ale] + ale2) + \u20ac you're lucky!</p>" : 1E4 < a && (b.getElementById("logros5-1").innerHTML = "<p>Your first 5+1 match took " + a + " years!! Better late than never!! Your prize would have been " + (w[ale] + ale2) + "\u20ac</p>"), 1 == aleatorio && $("<p>Your quick pick for this 5+1 prize was: <b>" +
                                                                                arr[0] + "</b> | <b>" + arr[1] + "</b> | <b>" + arr[2] + "</b> | <b>" + arr[3] + "</b> | <b>" + arr[4] + "</b> | &#10025;<b>" + est[0] + "</b>  &#10025;<b>" + est[1] + "</b></p>").appendTo("#logros5-1")); e[11]++; 1 == e[11] && (c = w[ale] + ale2, u = f - 2 * n, c = { xUsuario: usuario, xToken: token, xNick: nick, xA: ale, xA2: ale2, xEuro1: arr[0], xEuro2: arr[1], xEuro3: arr[2], xEuro4: arr[3], xEuro5: arr[4], xEuro6: est[0], xEuro7: est[1], xPremio: "5+1", xCantidad: c, xSemanal: sorteosSem, xTotal: n, xGanado: f, xBalance: u, xAno: a, xMes: k, xDia: t, xSorteo: n }, $.ajax({
                                                                                    url: "https://www.cuandomevaatocar.com/includes/puntuaciones-eur.php",
                                                                                    type: "POST", dataType: "json", data: c, success: function (q, h, D) {
                                                                                        "success" == q.status && ("n" != nick ? $("#logros5-1").append('<div class="enviarhof"><div class="marcohof"><div class="imagenhof"><img width="100%" src="https://www.cuandomevaatocar.com/img/hall-of-fame.png" alt="Prize saved to Hall Of Fame"></div><div class="formhof"><h3><span>New record! This result is among the best!</span></h3><h3><span>Your prize was saved to </span></h3><h2><span><a href="https://www.cuandomevaatocar.com/en/hall-of-fame/euromillions/">Hall of Fame</a></span></h2></div></div></div><div class="clear"></div>') :
                                                                                            $("#logros5-1").append('<div class="enviarhof"><div class="marcohof"><div class="imagenhof"><img width="100%" src="https://www.cuandomevaatocar.com/img/hall-of-fame.png" alt="Prize saved to Hall Of Fame"></div><div class="formhof"><h3><span>New record! This result is among the best!</span></h3><form id="formoid51" action="https://www.cuandomevaatocar.com/includes/actualizarnombre-eur.php" title="" method="post"><div class="hofizq"><label class="title">Name or nick</label><input type="text" id="xNick51" name="xNick51" maxlength="12" required pattern="[a-zA-Z0-9 ]+" ><h5>Only letters and numbers, no special characters. If you leave it blank you will appear as anonymous</h5><input type="hidden" id="xUsuario51" name="xUsuario51" value=""><input type="hidden" id="xToken51" name="xToken51" value=""><br>How do you want your combination to be shown?<br><input type="radio" name="xPriv" value="0" checked>Complete <span>(Example: 2 | 6 | 11 | 27 | 32 | &#10025; 2 | &#10025; 9 )</span><br><input type="radio" name="xPriv" value="1">Incomplete <span>(Example: ** | 6 | 11 | ** | 32 | &#10025; ** | &#10025; 9 )</span><br><input type="radio" name="xPriv" value="2">Hidden <span>(Example: ** | ** | ** | ** | ** | &#10025; ** |  &#10025; ** )</span></div><div class="hofder"><input type="submit" id="submitButton51" name="submitButton51" value="Save"></div></form></div></div></div><div class="clear"></div>'))
                                                                                    },
                                                                                    error: function (q, h, D) { }
                                                                                })); ga("send", "event", { eventCategory: "Euromillones - Premio de 5+1", eventAction: usuario, eventLabel: a }); H = 0 == H ? w[ale] + ale2 + .07 * ale : (H + w[ale] + ale2) / 2; b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) + " \u20ac"; b.getElementById("d5-1").innerHTML = "Match 5 + 1:  <b>" + e[11] + "</b>"; b.getElementById("media5-1").innerHTML = H.toFixed(2) + \u20ac; c = $("#indicador").position().left; g = l + 13; 6 > g && (g = 6); $("#premiosldt ul").append($("<li></li>").addClass("icono5-1").css({ left: c, width: g }));
                        1E6 == duracion && (ea = !0, clearTimeout(E), ja()); 3 < e[11] && 500 < 100 * f / B && (c = confirm("Will you behave?"), window.location.href = 1 == c ? "https://www.cuandomevaatocar.com" : "https://www.google.com"); break; case "5-2": ale2 = Math.ceil(3E6 * Math.random()) + 3E4, ale = r[0], f = f + z[ale] + ale2, 0 == e[12] && (0 == a && 0 == k ? b.getElementById("logros5-2").innerHTML = "<p>You couldn't have done better! LUCKY BASTARD! You hit the jackpot in just " + t + " days!! THAT'S LUCKING OUT!! RUN TO YOUR NEAREST RETAILER! NOW!! Your prize would have been " +
                            (z[ale] + ale2) + "\u20ac</p>" : 0 == a ? b.getElementById("logros5-2").innerHTML = "<p>UNBELIEVABLE!! You hit the jackpot in " + k + " months!! Congratulations!! Your prize would have been " + (z[ale] + ale2) + "\u20ac</p>" : 1 == a ? b.getElementById("logros5-2").innerHTML = "<p>AWESOME!! You hit the jackpot in a year and " + k + " months!! Your prize would have been " + (z[ale] + ale2) + "\u20ac</p>" : 5 <= a && 10 >= a ? b.getElementById("logros5-2").innerHTML = "<p>BRAVO! You won the jackpot in " + a + " years!! Your prize would have been " + (z[ale] +
                                ale2) + "\u20ac</p>" : 11 <= a && 25 >= a ? b.getElementById("logros5-2").innerHTML = "<p>You won the jackpot in " + a + " years!! You're luckiest than 99,9999% of people!! Your prize would have been " + (z[ale] + ale2) + "\u20ac</p>" : 26 <= a && 80 >= a ? b.getElementById("logros5-2").innerHTML = "<p>You won the jackpot in " + a + " years!! Your prize would have been " + (z[ale] + ale2) + "\u20ac</p>" : 81 <= a && 499 >= a ? b.getElementById("logros5-2").innerHTML = "<p>You won the jackpot in " + a + " years. It seems late but actually it's soon! Your prize would have been " +
                                    (z[ale] + ale2) + "\u20ac</p>" : 500 <= a && 999 >= a ? b.getElementById("logros5-2").innerHTML = "<p>You won the jackpot in " + a + " years!! It has been a long time coming but it is acceptable! Your prize would have been " + (z[ale] + ale2) + "\u20ac</p>" : 500 <= a && 999 >= a ? b.getElementById("logros5-2").innerHTML = "<p>You won the jackpot in " + a + " years!! It's soon! Your prize would have been " + (z[ale] + ale2) + "\u20ac</p>" : 1E3 <= a && 1E4 >= a ? b.getElementById("logros5-2").innerHTML = "<p>You won the jackpot in " + a + " years!! Your prize would have been " +
                                        (z[ale] + ale2) + "\u20ac you're lucky!</p>" : 1E4 < a && (b.getElementById("logros5-2").innerHTML = "<p>You won the jackpot in " + a + " years!! Better late than never!! Your prize would have been " + (z[ale] + ale2) + "\u20ac</p>"), 1 == aleatorio && $("<p>Your quick pick for this 5+2 prize was: <b>" + arr[0] + "</b> | <b>" + arr[1] + "</b> | <b>" + arr[2] + "</b> | <b>" + arr[3] + "</b> | <b>" + arr[4] + "</b> | &#10025;<b>" + est[0] + "</b>  &#10025;<b>" + est[1] + "</b></p>").appendTo("#logros5-2")), e[12]++, 1 == e[12] && (c = z[ale] + ale2, u = f - 2 * n, c = {
                                            xUsuario: usuario,
                                            xToken: token, xNick: nick, xA: ale, xA2: ale2, xEuro1: arr[0], xEuro2: arr[1], xEuro3: arr[2], xEuro4: arr[3], xEuro5: arr[4], xEuro6: est[0], xEuro7: est[1], xPremio: "5+2", xCantidad: c, xSemanal: sorteosSem, xTotal: n, xGanado: f, xBalance: u, xAno: a, xMes: k, xDia: t, xSorteo: n
                                        }, $.ajax({
                                            url: "https://www.cuandomevaatocar.com/includes/puntuaciones-eur.php", type: "POST", dataType: "json", data: c, success: function (q, h, D) {
                                                "success" == q.status && ("n" != nick ? $("#logros5-2").append('<div class="enviarhof"><div class="marcohof"><div class="imagenhof"><img width="100%" src="https://www.cuandomevaatocar.com/img/hall-of-fame.png" alt="Prize saved to Hall Of Fame"></div><div class="formhof"><h3><span>New record! This result is among the best!</span></h3><h3><span>Your prize was saved to </span></h3><h2><span><a href="https://www.cuandomevaatocar.com/en/hall-of-fame/euromillions/">Hall of Fame</a></span></h2></div></div></div><div class="clear"></div>') :
                                                    $("#logros5-2").append('<div class="enviarhof"><div class="marcohof"><div class="imagenhof"><img width="100%" src="https://www.cuandomevaatocar.com/img/hall-of-fame.png" alt="Prize saved to Hall Of Fame"></div><div class="formhof"><h3><span>New record! This result is among the best!</span></h3><form id="formoid52" action="https://www.cuandomevaatocar.com/includes/actualizarnombre-eur.php" title="" method="post"><div class="hofizq"><label class="title">Name or nick</label><input type="text" id="xNick52" name="xNick52" maxlength="12" required pattern="[a-zA-Z0-9 ]+" ><h5>Only letters and numbers, no special characters. If you leave it blank you will appear as anonymous</h5><input type="hidden" id="xUsuario52" name="xUsuario52" value=""><input type="hidden" id="xToken52" name="xToken52" value=""><br>How do you want your combination to be shown?<br><input type="radio" name="xPriv" value="0" checked>Complete <span>(Example: 2 | 6 | 11 | 27 | 32 | &#10025; 2 | &#10025; 9 )</span><br><input type="radio" name="xPriv" value="1">Incomplete <span>(Example: ** | 6 | 11 | ** | 32 | &#10025; ** | &#10025; 9 )</span><br><input type="radio" name="xPriv" value="2">Hidden <span>(Example: ** | ** | ** | ** | ** | &#10025; ** |  &#10025; ** )</span></div><div class="hofder"><input type="submit" id="submitButton52" name="submitButton52" value="Save"></div></form></div></div></div><div class="clear"></div>'))
                                            },
                                            error: function (q, h, D) { }
                                        })), ga("send", "event", { eventCategory: "Euromillones - Premio de 5+2", eventAction: usuario, eventLabel: a }), b.getElementById("ganado").innerHTML = parseFloat(f).toFixed(2) + " \u20ac", b.getElementById("d5-2").innerHTML = "Match 5 + 2:  <b>" + e[12] + "</b>", b.getElementById("media5-2").innerHTML = H.toFixed(2) + \u20ac, c = $("#indicador").position().left, g = l + 16, 9 > g && (g = 9), $("#premiosldt ul").append($("<li></li>").addClass("icono5-2").css({ left: c, width: g })), ea = !0, clearTimeout(E), ja(), 2 < e[12] &&
                                        500 < 100 * f / B && (c = confirm("Will you behave?"), window.location.href = 1 == c ? "https://www.cuandomevaatocar.com" : "https://www.google.com")
                }u = f - B; b.getElementById("invertido").innerHTML = parseFloat(B).toFixed(2) + " \u20ac"; b.getElementById("diferencia").innerHTML = parseFloat(u).toFixed(2) + " \u20ac"; 0 < u ? ($("#diferencia").addClass("difverde"), u > ka && (ka = u, b.getElementById("logros0").innerHTML = "<p>Your best positive balance was " + parseFloat(ka).toFixed(2) + "\u20ac during year " + a + "</p>")) : $("#diferencia").removeClass("difverde");
        document.getElementById("ano").innerHTML = a; document.getElementById("mes").innerHTML = k; document.getElementById("dia").innerHTML = t; if (Da[ra] == n || 0 == n % 10400) ra++, b = 100 * f / B, 100 < b && (b = 100), b = parseFloat(b.toFixed(2)), $.ajax({ url: "https://www.cuandomevaatocar.com/includes/porcentajes-eur.php", type: "POST", encoding: "UTF-8", dataType: "json", data: { xUsuario: usuario, xToken: token, xPct: b, xSorteos: n, xAnu: A }, success: function (q, h, D) { }, error: function (q, h, D) { } }); b = duracion * A; 1 == ea && (b = n); n == b ? (clearTimeout(E), ja()) : (n++, E = setTimeout(I, delay))
    } function ja() {
        $("#texttit1").text("");
        var b = 100 * f / B; 10 >= b ? document.getElementById("logrosf").innerHTML = "<p>Your luck was terrible! It was difficult to do worse...</p>" : 11 <= b && 18 >= b ? document.getElementById("logrosf").innerHTML = "<p>Just plain terrible. You were quite unlucky.</p>" : 19 <= b && 24 >= b ? document.getElementById("logrosf").innerHTML = "<p>You could do worse, but your results were not particularly good.</p>" : 25 <= b && 26 >= b ? document.getElementById("logrosf").innerHTML = "<p>Your luck is slightly below the average.</p>" : 27 <= b && 29 >= b ? document.getElementById("logrosf").innerHTML =
            "<p>Your luck was average</p>" : 30 <= b && 34 >= b ? document.getElementById("logrosf").innerHTML = "<p>Your luck was slightly above the average.</p>" : 35 <= b && 45 >= b ? document.getElementById("logrosf").innerHTML = "<p>You were luckier than most users</p>" : 46 <= b && 61 >= b ? document.getElementById("logrosf").innerHTML = "<p>We can almost say your luck was good.</p>" : 62 <= b && 71 >= b ? document.getElementById("logrosf").innerHTML = "<p>Your results were much better than the average</p>" : 72 <= b && 82 >= b ? document.getElementById("logrosf").innerHTML =
                "<p>You nearly got the return on investment. Your luck was acceptable.</p>" : 83 <= b && 99 >= b ? document.getElementById("logrosf").innerHTML = "<p>You did pretty well! Your luck was better than the average yet your final balance was negative by little...</p>" : 100 <= b && 119 >= b ? document.getElementById("logrosf").innerHTML = "<p>BRAVO! You end up with a positive balance!</p>" : 120 <= b && 140 >= b ? document.getElementById("logrosf").innerHTML = "<p>Amazing! Luck is on your side!!</p>" : 141 <= b && (document.getElementById("logrosf").innerHTML =
                    "<p>You're luckiest than 99,9999% of people!!!</p>"); 100 > b ? document.getElementById("logrosf2").innerHTML = "<p>You won in prizes " + parseFloat(b.toFixed(2)) + "% of the investment</p>" : document.getElementById("logrosf2").innerHTML = "<p>You have recovered 100% of the investment and besides you have won " + Math.round(u) + "\u20ac!!<br>It could be the right moment to retire!</p>"; $("#logrosf").css("margin-bottom", 15); $("#botones").css("display", "block"); $("#redes").css("display", "block"); $("#btndetener").css("display",
                        "none"); 6 > vueltas ? document.getElementById("btncontinuar").innerHTML = "<h2>CONTINUE</h2><span>to " + fa[vueltas + 1] + "</span>" : 7 < vueltas ? document.getElementById("btncontinuar").innerHTML = "<h2>CONTINUE</h2><span>Grasp all, lose all</span>" : document.getElementById("btncontinuar").innerHTML = "<h2>CONTINUE</h2><span>" + fa[vueltas + 1] + "</span>"; $("#btncontinuar").addClass("btnfin"); document.getElementById("btnvolver").innerHTML = "<h2>BACK</h2><span>to homepage</span>"; $("#btnvolver").addClass("btnfin"); document.getElementById("btnrepetir").innerHTML =
                            "<h2>REPEAT</h2><span>combination and period</span>"; $("#btnrepetir").addClass("btnfin"); document.getElementById("btnfb").innerHTML = "<span>Share</span>"; $("#btnfb").addClass("facebook"); document.getElementById("btntw").innerHTML = "<span>Twit</span>"; $("#btntw").addClass("twitter"); $("body").hasClass("blurred") && alert(" " + a + " years have passed!")
    } Array.prototype.indexOf || (Array.prototype.indexOf = function (b) { return jQuery.inArray(b, this) }); vueltas = parseFloat(vueltas); var Ea = [1, 5, 10, 25, 50, 100, 1E3, 1E6,
        1E7], fa = "1 year;5 years;10 years;25 years;50 years;100 years;1000 years;Until 5+1 appears;Until 5+2 appears;Undefined".split(";"), A = 52 * sorteosSem, ra = 0, Da = [104, 520, 1040, 2600, 5200, 10400, 104E3]; $("#tucombinacion").html("Your combination: <b>" + arr[0] + "</b> | <b>" + arr[1] + "</b> | <b>" + arr[2] + "</b> | <b>" + arr[3] + "</b> | <b>" + arr[4] + "</b> | &#10025;<b>" + est[0] + "</b>  &#10025;<b>" + est[1] + "</b>"); $("#textosorteos").html("<p>Weekly draws: " + sorteosSem + "</p>"); var y = document.body.clientWidth, sa = y, l = 3, J = 2, ua =
            [3, 4, 5, 3, 4, 5, 3, 4, 5, 4, 4, 3, 4], va = [6, 7, 8, 9, 10, 9, 8, 7, 6, 8, 7, 7, 7], wa = [7, 8, 9, 10, 11, 12, 13, 14, 15, 12, 11, 9, 10], xa = [15, 12, 10, 14, 13, 9, 12, 15, 12, 10, 14, 12, 12], ya = [11, 18, 15, 16, 15, 17, 14, 16, 15, 17, 14, 15, 14], za = [13, 24, 25, 23, 25, 15, 10, 22, 24, 24, 16, 24, 24], Aa = [45, 65, 75, 58, 48, 50, 30, 69, 37, 54, 47, 46, 46], Ba = [95, 62, 110, 108, 134, 95, 150, 110, 108, 124, 85, 134, 148], Ca = [150, 116, 209, 206, 437, 150, 616, 209, 890, 237, 222, 150, 150], aa = [6896, 3849, 5519, 3475, 2974, 5569, 4896, 3849, 7519, 3475, 2674, 2506, 2674], v = [52716, 46198, 32331, 85155, 67840, 256211, 152235,
                52716, 46198, 100331, 85155, 59940, 59940], w = [1263580, 194005, 226316, 1021863, 1412166, 685059, 263580, 226316, 1021863, 1412166, 685059, 623023, 923023], z = [125543227, 37632166, 25543227, 37632166, 25543227, 37632166, 25543227, 37632166, 25543227, 37632166, 25543227, 125543227, 25543227], f = 0, B = 0, u = 0, e = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], E, d = 10, ia = y / (d * A), ma = 2, n = 1, F = 0, L = 0, O = 0, R = 0, U = 0, V = 0, W = 0, X = 0, Y = 0, Z = 0, ba = 0, ca = 0, H = 0; $("#pf2").text(Math.round(d / 2) + " years"); $("#pf3").text(Math.round(d) + " years"); $("#ldt ul").append("<li id= tr" + d +
                    ">0</li><li id= t" + d + ">" + d / 2 + "</li>"); $("#tr" + d).css({ "background-color": "#cccccc", width: "50%" }); $("#t" + d).css({ "background-color": "#f3f3f3", width: "50%" }); $("#textoldt").html("Matches shown <span class='color-2-0'> 2+0</span>, <span class='color-2-1'> 2+1</span>, <span class='color-1-2'> 1+2</span>, <span class='color-3-0'> 3+0</span>, <span class='color-3-1'> 3+1</span>, <span class='color-2-2'> 2+2</span>, <span class='color-3-2'> 3+2</span>, <span class='color-4-0'> 4+0</span>, <span class='color-4-1'> 4+1</span>, <span class='color-4-2'> 4+2</span>, <span class='color-5-0'> 5+0</span>, <span class='color-5-1'> 5+1</span> and <span class='color-5-2'> 5+2</span>");
    var r, la, ha, K, a = 0, k = 0, t = 1, M = 0, N = 0, P = 0, Q = 0, S = 0, T = 0, na = 0, oa = 0, pa = 0, ka = 0, qa, da = 99999, ea = !1; I(); $.fn.toggleClick = function () { var b = arguments; return this.click(function () { var c = $(this).data("iteration") || 0; b[c].apply(this, arguments); c = (c + 1) % b.length; $(this).data("iteration", c) }) }; $("#btndetener").toggleClick(function () {
        $(this).text("CONTINUE"); $(this).toggleClass("verde"); $("#texttit1").text("Simulation stopped"); var b = 100 * f / B; 100 > b ? document.getElementById("logrosf2").innerHTML = "<p>You have recovered " +
            parseFloat(b.toFixed(2)) + "% of the investment</p>" : document.getElementById("logrosf2").innerHTML = "<p>You have recovered 100% of the investment and besides you have won " + Math.round(u) + "\u20ac!!<br>It could be the right moment to retire!</p>"; clearTimeout(E)
    }, function () { $(this).text("Pause"); $(this).toggleClass("verde"); $("#texttit1").text("Simulation in progress"); document.getElementById("logrosf2").innerHTML = ""; clearTimeout(E); n++; E = setTimeout(I, delay) }); $(document).on("submit", "#formoid42", function (b) {
        document.getElementById("xUsuario42").value =
        usuario; document.getElementById("xToken42").value = token; var c = $(this).serializeArray(), p = $(this).attr("action"); $.ajax({
            url: p, type: "POST", dataType: "json", data: c, contentType: "application/x-www-form-urlencoded", success: function (m, C, x) { "actualizado" == m.status && (nick = "p", $(".formhof").html('<h3><span>New record! This result is among the best!</span></h3><h3><span>Your prize was saved to </span></h3><h2><span><a href="https://www.cuandomevaatocar.com/en/hall-of-fame/euromillions/">Hall of Fame</a></span></h2>')) }, error: function (m, C,
                x) { }
        }); b.preventDefault(); return !1
    }); $(document).on("submit", "#formoid50", function (b) {
        document.getElementById("xUsuario50").value = usuario; document.getElementById("xToken50").value = token; var c = $(this).serializeArray(), p = $(this).attr("action"); $.ajax({
            url: p, type: "POST", dataType: "json", data: c, contentType: "application/x-www-form-urlencoded", success: function (m, C, x) { "actualizado" == m.status && (nick = "p", $(".formhof").html('<h3><span>New record! This result is among the best!</span></h3><h3><span>Your prize was saved to </span></h3><h2><span><a href="https://www.cuandomevaatocar.com/en/hall-of-fame/euromillions/">Hall of Fame</a></span></h2>')) },
            error: function (m, C, x) { }
        }); b.preventDefault(); return !1
    }); $(document).on("submit", "#formoid51", function (b) {
        document.getElementById("xUsuario51").value = usuario; document.getElementById("xToken51").value = token; var c = $(this).serializeArray(), p = $(this).attr("action"); $.ajax({
            url: p, type: "POST", dataType: "json", data: c, contentType: "application/x-www-form-urlencoded", success: function (m, C, x) { "actualizado" == m.status && (nick = "p", $(".formhof").html('<h3><span>New record! This result is among the best!</span></h3><h3><span>Your prize was saved to </span></h3><h2><span><a href="https://www.cuandomevaatocar.com/en/hall-of-fame/euromillions/">Hall of Fame</a></span></h2>')) },
            error: function (m, C, x) { }
        }); b.preventDefault(); return !1
    }); $(document).on("submit", "#formoid52", function (b) {
        document.getElementById("xUsuario52").value = usuario; document.getElementById("xToken52").value = token; var c = $(this).serializeArray(), p = $(this).attr("action"); $.ajax({
            url: p, type: "POST", dataType: "json", data: c, contentType: "application/x-www-form-urlencoded", success: function (m, C, x) { "actualizado" == m.status && (nick = "p", $(".formhof").html('<h3><span>New record! This result is among the best!</span></h3><h3><span>Your prize was saved to </span></h3><h2><span><a href="https://www.cuandomevaatocar.com/en/hall-of-fame/euromillions/">Hall of Fame</a></span></h2>')) },
            error: function (m, C, x) { }
        }); b.preventDefault(); return !1
    }); $("#totalsemanal").text(parseFloat(precioSort * sorteosSem).toFixed(2)); $("#velocidad2_opc").change(function () { delay = $(this).attr("value") }); $("#btnrepetir").click(function () { window.location.href = "https://www.cuandomevaatocar.com/en/euromillions/simulator/" }); $("#btnvolver").click(function () { window.location.href = "https://www.cuandomevaatocar.com/en/" }); $("#btncontinuar").click(function () {
        9 > vueltas && vueltas++; ea = !1; document.getElementById("logrosf").innerHTML =
            ""; document.getElementById("logrosf2").innerHTML = ""; $("#logrosf").css("margin-bottom", 0); $("#btnfb").removeClass("facebook"); $("#btntw").removeClass("twitter"); document.getElementById("btnfb").innerHTML = ""; document.getElementById("btntw").innerHTML = ""; $("#texttit1").text("Simulation in progress"); $("#botones").css("display", "none"); $("#redes").css("display", "none"); $("#btndetener").css("display", "block"); duracion = Ea[vueltas]; $("#textoperiodo").html("<p>Period: " + fa[vueltas] + " </p>"); n++; ga("send",
                "event", { eventCategory: "Euromillions - Continue", eventAction: usuario, eventLabel: fa[vueltas] }); E = setTimeout(I, delay)
    }); 450 > y ? $("#ccb1").text("draws") : $("#ccb1").text("draws n\u00ba"); $(window).resize(function () { y = document.body.clientWidth; ia = y / (d * A); 450 > y ? $("#ccb1").text("draws") : $("#ccb1").text("draws n\u00ba"); $("#premiosldt li").each(function (b) { b = $(this).position().left * y / sa; $(this).css({ left: b }) }); sa = y })
    $("a[href^='/']").each(function() {
        var href = $(this).attr("href");
        $(this).attr("href", "https://www.cuandomevaatocar.com" + href);
    });
});

